In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [4]:
data = pd.read_csv("C:/Users/YarKhan/Desktop/DeepLearning/train.csv")
data

,v.id,on road old,on road now,years,km,rating,condition,economy,top speed,hp,torque,current price
0,1,535651,798186,3,78945,1,2,14,177,73,123,351318.0
1,2,591911,861056,6,117220,5,9,9,148,74,95,285001.5
2,3,686990,770762,2,132538,2,8,15,181,53,97,215386.0
3,4,573999,722381,4,101065,4,3,11,197,54,116,244295.5
4,5,691388,811335,6,61559,3,9,12,160,53,105,531114.5
...,...,...,...,...,...,...,...,...,...,...,...,...
995,996,633238,743850,5,125092,1,6,11,171,95,97,190744.0
996,997,599626,848195,4,83370,2,9,14,161,101,120,419748.0
997,998,646344,842733,7,86722,1,8,9,196,113,89,405871.0
998,999,535559,732439,2,140478,4,5,9,184,112,128,74398.0
999,1000,590105,779743,5,67295,4,2,8,199,99,96,414938.5

In [5]:
data.shape

(1000, 12)

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   v.id           1000 non-null   int64
 1   on road old    1000 non-null   int64
 2   on road now    1000 non-null   int64
 3   years          1000 non-null   int64
 4   km             1000 non-null   int64
 5   rating         1000 non-null   int64
 6   condition      1000 non-null   int64
 7   economy        1000 non-null   int64
 8   top speed      1000 non-null   int64
 9   hp             1000 non-null   int64
 10  torque         1000 non-null   int64
 11  current price  1000 non-null   float64
dtypes: float64(1), int64(11)
memory usage: 93.9 KB

In [13]:
data.isnull().sum()

v.id             0
on road old      0
on road now      0
years            0
km               0
rating           0
condition        0
economy          0
top speed        0
hp               0
torque           0
current price    0
dtype: int64

In [20]:
data.count()

v.id             1000
on road old      1000
on road now      1000
years            1000
km               1000
rating           1000
condition        1000
economy          1000
top speed        1000
hp               1000
torque           1000
current price    1000
dtype: int64

In [12]:
data.nunique()

v.id             1000
on road old       998
on road now       998
years               6
km                997
rating              5
condition          10
economy             8
top speed          66
hp                 71
torque             73
current price    1000
dtype: int64

In [16]:
data.describe()

,v.id,on road old,on road now,years,km,rating,condition,economy,top speed,hp,torque,current price
count,1000.000000,1000.000000,1000.0000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1000.00000,1000.000000,1000.00000
mean,500.500000,601648.286000,799131.3970,4.561000,100274.430000,2.988000,5.592000,11.625000,166.89300,84.54600,103.423000,308520.24250
std,288.819436,58407.246204,57028.9502,1.719079,29150.463233,1.402791,2.824449,2.230549,19.28838,20.51694,21.058716,126073.25915
min,1.000000,500265.000000,700018.0000,2.000000,50324.000000,1.000000,1.000000,8.000000,135.00000,50.00000,68.000000,28226.50000
25%,250.750000,548860.500000,750997.7500,3.000000,74367.500000,2.000000,3.000000,10.000000,150.00000,67.00000,85.000000,206871.75000
50%,500.500000,601568.000000,798168.0000,5.000000,100139.500000,3.000000,6.000000,12.000000,166.00000,84.00000,104.000000,306717.75000
75%,750.250000,652267.250000,847563.2500,6.000000,125048.000000,4.000000,8.000000,13.000000,184.00000,102.00000,121.000000,414260.87500
max,1000.000000,699859.000000,899797.0000,7.000000,149902.000000,5.000000,10.000000,15.000000,200.00000,120.00000,140.000000,584267.50000

In [19]:
data.columns

Index(['v.id', 'on road old', 'on road now', 'years', 'km', 'rating',
       'condition', 'economy', 'top speed', 'hp', 'torque', 'current price'],
      dtype='object')

In [25]:
data = data.drop("v.id", axis = 1)

In [26]:
data

,on road old,on road now,years,km,rating,condition,economy,top speed,hp,torque,current price
0,535651,798186,3,78945,1,2,14,177,73,123,351318.0
1,591911,861056,6,117220,5,9,9,148,74,95,285001.5
2,686990,770762,2,132538,2,8,15,181,53,97,215386.0
3,573999,722381,4,101065,4,3,11,197,54,116,244295.5
4,691388,811335,6,61559,3,9,12,160,53,105,531114.5
...,...,...,...,...,...,...,...,...,...,...,...
995,633238,743850,5,125092,1,6,11,171,95,97,190744.0
996,599626,848195,4,83370,2,9,14,161,101,120,419748.0
997,646344,842733,7,86722,1,8,9,196,113,89,405871.0
998,535559,732439,2,140478,4,5,9,184,112,128,74398.0
999,590105,779743,5,67295,4,2,8,199,99,96,414938.5

In [27]:
tensor_df = tf.constant(data, dtype = tf.float32)
tensor_df

<tf.Tensor: shape=(1000, 11), dtype=float32, numpy=
array([[5.356510e+05, 7.981860e+05, 3.000000e+00, ..., 7.300000e+01,
        1.230000e+02, 3.513180e+05],
       [5.919110e+05, 8.610560e+05, 6.000000e+00, ..., 7.400000e+01,
        9.500000e+01, 2.850015e+05],
       [6.869900e+05, 7.707620e+05, 2.000000e+00, ..., 5.300000e+01,
        9.700000e+01, 2.153860e+05],
       ...,
       [6.463440e+05, 8.427330e+05, 7.000000e+00, ..., 1.130000e+02,
        8.900000e+01, 4.058710e+05],
       [5.355590e+05, 7.324390e+05, 2.000000e+00, ..., 1.120000e+02,
        1.280000e+02, 7.439800e+04],
       [5.901050e+05, 7.797430e+05, 5.000000e+00, ..., 9.900000e+01,
        9.600000e+01, 4.149385e+05]], dtype=float32)>

In [28]:
tensor_df = tf.random.shuffle(tensor_df)
tensor_df

<tf.Tensor: shape=(1000, 11), dtype=float32, numpy=
array([[5.970160e+05, 7.878040e+05, 6.000000e+00, ..., 8.000000e+01,
        7.900000e+01, 3.926355e+05],
       [5.040160e+05, 7.919330e+05, 4.000000e+00, ..., 1.120000e+02,
        9.600000e+01, 2.216920e+05],
       [5.161580e+05, 7.784500e+05, 7.000000e+00, ..., 5.200000e+01,
        1.000000e+02, 8.723450e+04],
       ...,
       [6.990230e+05, 8.386540e+05, 7.000000e+00, ..., 9.400000e+01,
        1.390000e+02, 2.758375e+05],
       [6.581770e+05, 7.598790e+05, 7.000000e+00, ..., 7.400000e+01,
        1.190000e+02, 4.686660e+05],
       [6.245380e+05, 7.742950e+05, 5.000000e+00, ..., 9.900000e+01,
        1.130000e+02, 1.809120e+05]], dtype=float32)>

In [31]:
X = tensor_df[:, 2:-1]
X

<tf.Tensor: shape=(1000, 8), dtype=float32, numpy=
array([[6.00000e+00, 7.44440e+04, 5.00000e+00, ..., 1.88000e+02,
        8.00000e+01, 7.90000e+01],
       [4.00000e+00, 1.06653e+05, 4.00000e+00, ..., 1.94000e+02,
        1.12000e+02, 9.60000e+01],
       [7.00000e+00, 1.45395e+05, 3.00000e+00, ..., 1.88000e+02,
        5.20000e+01, 1.00000e+02],
       ...,
       [7.00000e+00, 1.22196e+05, 1.00000e+00, ..., 1.94000e+02,
        9.40000e+01, 1.39000e+02],
       [7.00000e+00, 7.05640e+04, 1.00000e+00, ..., 1.76000e+02,
        7.40000e+01, 1.19000e+02],
       [5.00000e+00, 1.33782e+05, 5.00000e+00, ..., 1.86000e+02,
        9.90000e+01, 1.13000e+02]], dtype=float32)>

In [32]:
y = tensor_df[:, -1]
y = tf.expand_dims(y, axis = -1)
y

<tf.Tensor: shape=(1000, 1), dtype=float32, numpy=
array([[392635.5],
       [221692. ],
       [ 87234.5],
       [424305. ],
       [385556.5],
       [172032.5],
       [213768.5],
       [291810. ],
       [153371.5],
       [206836.5],
       [350647.5],
       [304445. ],
       [405871. ],
       [352345. ],
       [179711.5],
       [457463. ],
       [315925. ],
       [315131.5],
       [367734.5],
       [427132.5],
       [174399. ],
       [212553.5],
       [452633. ],
       [315866.5],
       [360008. ],
       [172859.5],
       [203811.5],
       [227669. ],
       [238638.5],
       [112864.5],
       [420083. ],
       [404800.5],
       [347784.5],
       [190949. ],
       [435007.5],
       [299609. ],
       [382794.5],
       [417940. ],
       [438032.5],
       [160597.5],
       [458537. ],
       [458463.5],
       [ 53040. ],
       [344405.5],
       [497572.5],
       [153991. ],
       [443528. ],
       [220518. ],
       [267953.5],
       [389610. ],
       [380289.5],
       [269326. ],
       [278993.5],
       [423507. ],
       [250309.5],
       [120869.5],
       [297625. ],
       [400257. ],
       [134035. ],
       [251317.5],
       [169125.5],
       [505336.5],
       [452931. ],
       [131893.5],
       [169784. ],
       [425777.5],
       [103742.5],
       [304216.5],
       [204833.5],
       [197320. ],
       [531114.5],
       [364155.5],
       [240353.5],
       [453672.5],
       [414035. ],
       [446487.5],
       [457581. ],
       [330908.5],
       [174352.5],
       [311973. ],
       [312323.5],
       [492681.5],
       [558355. ],
       [418934. ],
       [441561.5],
       [180948. ],
       [306982.5],
       [307008. ],
       [496514. ],
       [502708.5],
       [158031.5],
       [332478.5],
       [311109. ],
       [221781. ],
       [432159.5],
       [388376. ],
       [ 77277. ],
       [146568. ],
       [370175. ],
       [398023. ],
       [181414.5],
       [466371. ],
       [239746. ],
       [218814. ],
       [354900. ],
       [537014. ],
       [299655. ],
       [ 87769. ],
       [408860.5],
       [313619.5],
       [499647. ],
       [198503. ],
       [512885.5],
       [200408.5],
       [288556.5],
       [321363. ],
       [237204. ],
       [483663.5],
       [360647.5],
       [339335.5],
       [340112. ],
       [396244. ],
       [377507. ],
       [413424.5],
       [272437.5],
       [340760. ],
       [547746. ],
       [379725. ],
       [352284.5],
       [470373. ],
       [145898.5],
       [206335.5],
       [252549.5],
       [313879. ],
       [409312.5],
       [351318. ],
       [157507. ],
       [475001.5],
       [397183. ],
       [317681.5],
       [329639. ],
       [240296.5],
       [ 97969. ],
       [301591. ],
       [356606.5],
       [262576. ],
       [229982. ],
       [352318.5],
       [415103. ],
       [178180.5],
       [ 69231.5],
       [331819.5],
       [528794. ],
       [207552. ],
       [498712. ],
       [476969.5],
       [382676. ],
       [545171. ],
       [ 28226.5],
       [486308.5],
       [181428.5],
       [269532.5],
       [184092.5],
       [180476.5],
       [301042.5],
       [243549.5],
       [379608. ],
       [122843.5],
       [156513. ],
       [149899.5],
       [256331.5],
       [167281.5],
       [156825.5],
       [105427.5],
       [157874. ],
       [527409.5],
       [451140.5],
       [295553.5],
       [ 71314. ],
       [317168.5],
       [360410. ],
       [456554.5],
       [292520.5],
       [250771. ],
       [ 93190.5],
       [505223.5],
       [439166. ],
       [547069. ],
       [388209.5],
       [216302. ],
       [385031. ],
       [413066. ],
       [496671. ],
       [459095. ],
       [256356. ],
       [509506.5],
       [313095.5],
       [201188.5],
       [329538.5],
       [221132.5],
       [312164.5],
       [295013. ],
       [274453.5],
       [191566. ],
       [400444.5],
       [408203.5],
       [260231. ],
       [245796. ],
       [128632.5],
       [559074. ],
       [513722.5],
       [193067. ],
       [312593. ],
       [164382. ],
       [322951.5],
       [304354. ],
       [223885. ],
       [ 53470.5],
       [343416.5],
       [558253. ],
       [165741.5],
       [498148. ],
       [265955. ],
       [467074.5],
       [406657.5],
       [364898. ],
       [459914.5],
       [123719.5],
       [178991.5],
       [239214. ],
       [275781. ],
       [375370.5],
       [412014.5],
       [114860. ],
       [245810. ],
       [399055.5],
       [293841. ],
       [401120.5],
       [237954. ],
       [230797. ],
       [284094.5],
       [477912. ],
       [180368.5],
       [163225. ],
       [274172. ],
       [499185.5],
       [132159. ],
       [126070.5],
       [163814. ],
       [383570.5],
       [486590. ],
       [501920.5],
       [140596. ],
       [515722.5],
       [108921.5],
       [340777. ],
       [225669.5],
       [122139.5],
       [559108. ],
       [306745.5],
       [239815.5],
       [175810. ],
       [424781. ],
       [378071.5],
       [122225.5],
       [108741. ],
       [312454.5],
       [431060. ],
       [ 58384. ],
       [427496. ],
       [196639.5],
       [107147.5],
       [460780. ],
       [483708.5],
       [ 46920.5],
       [508328.5],
       [355175. ],
       [244640. ],
       [285001.5],
       [276805.5],
       [490000.5],
       [401011.5],
       [120092.5],
       [261732. ],
       [120583.5],
       [365136.5],
       [398998. ],
       [312469. ],
       [403213.5],
       [197266. ],
       [405505. ],
       [360675. ],
       [494345.5],
       [366878.5],
       [198738. ],
       [489368. ],
       [124847.5],
       [206591. ],
       [182219.5],
       [241487.5],
       [460075. ],
       [167794. ],
       [299129.5],
       [192853.5],
       [422497. ],
       [348000. ],
       [126957.5],
       [301081.5],
       [260801. ],
       [553901. ],
       [406349.5],
       [411701. ],
       [199313.5],
       [469084.5],
       [501662.5],
       [479896. ],
       [520084. ],
       [110229.5],
       [434336.5],
       [340165. ],
       [133006.5],
       [457880.5],
       [125721.5],
       [224533.5],
       [312703. ],
       [287675. ],
       [533610.5],
       [275385. ],
       [ 98242.5],
       [118348.5],
       [229749.5],
       [387321.5],
       [368522.5],
       [169954. ],
       [441863.5],
       [280123. ],
       [243006.5],
       [171620. ],
       [503307.5],
       [455824.5],
       [429669. ],
       [ 82848. ],
       [379491. ],
       [299019.5],
       [433602. ],
       [235251.5],
       [441865. ],
       [184900.5],
       [320603. ],
       [486699. ],
       [265799.5],
       [529318.5],
       [315841.5],
       [232526.5],
       [274357.5],
       [179077. ],
       [264576.5],
       [184571. ],
       [315959. ],
       [207352.5],
       [343595. ],
       [129863. ],
       [253867. ],
       [349780. ],
       [336181.5],
       [146527. ],
       [219127. ],
       [211528.5],
       [168854.5],
       [140061.5],
       [212546.5],
       [418871.5],
       [240926. ],
       [199798. ],
       [453069. ],
       [289117. ],
       [327454.5],
       [253853.5],
       [315403.5],
       [517366. ],
       [500679.5],
       [539377. ],
       [334502. ],
       [244229. ],
       [205716.5],
       [331263.5],
       [510929. ],
       [506401. ],
       [221510. ],
       [167998. ],
       [173847. ],
       [233987. ],
       [206883.5],
       [187305. ],
       [542371. ],
       [158741.5],
       [152879.5],
       [470890.5],
       [336038. ],
       [ 64531. ],
       [109367. ],
       [305652.5],
       [314523.5],
       [230428.5],
       [144124. ],
       [293875.5],
       [424107.5],
       [284462.5],
       [516466. ],
       [221412.5],
       [228875.5],
       [379991. ],
       [ 65467.5],
       [340720. ],
       [474281.5],
       [170104.5],
       [223369.5],
       [276960.5],
       [425567.5],
       [198511.5],
       [282821.5],
       [506854. ],
       [183465.5],
       [344495. ],
       [150076. ],
       [ 61928.5],
       [328698. ],
       [207480.5],
       [390756.5],
       [445538. ],
       [380231. ],
       [476955.5],
       [308376.5],
       [239400. ],
       [457793. ],
       [213739. ],
       [320008. ],
       [443423. ],
       [449650. ],
       [177509.5],
       [ 78924.5],
       [245854.5],
       [387089. ],
       [ 97526. ],
       [242709.5],
       [333091.5],
       [504643.5],
       [170838.5],
       [178642.5],
       [230090.5],
       [302929.5],
       [186388.5],
       [501083.5],
       [458833.5],
       [218983.5],
       [136079. ],
       [175012.5],
       [268200.5],
       [255901.5],
       [366732. ],
       [188131.5],
       [337917. ],
       [459833.5],
       [462397.5],
       [318858. ],
       [132026.5],
       [472081. ],
       [316184. ],
       [508432. ],
       [266341. ],
       [555336.5],
       [177933.5],
       [316387.5],
       [325176. ],
       [230080. ],
       [427079. ],
       [499121. ],
       [115462.5],
       [488457. ],
       [500164. ],
       [456827.5],
       [538075.5],
       [217562. ],
       [299645. ],
       [420075.5],
       [376446. ],
       [420401. ],
       [274075. ],
       [305002.5],
       [298023. ],
       [308867. ],
       [232718.5],
       [410403.5],
       [422439.5],
       [381960. ],
       [122567.5],
       [518845. ],
       [289049.5],
       [ 76772. ],
       [481862. ],
       [482353.5],
       [206678. ],
       [427590. ],
       [369149. ],
       [109828.5],
       [100927. ],
       [308643.5],
       [426796.5],
       [424290. ],
       [158951.5],
       [322684. ],
       [324373. ],
       [327075.5],
       [373735. ],
       [415493. ],
       [493806.5],
       [249603. ],
       [239923. ],
       [209639. ],
       [130112.5],
       [437540.5],
       [185485.5],
       [146223. ],
       [403886.5],
       [421655.5],
       [510361.5],
       [216831.5],
       [294502.5],
       [443735.5],
       [356189. ],
       [164649.5],
       [314576.5],
       [250955. ],
       [229110. ],
       [282496.5],
       [148734.5],
       [159647. ],
       [419713. ],
       [423584. ],
       [160150.5],
       [256476.5],
       [151080.5],
       [463054.5],
       [303506.5],
       [273674.5],
       [148491. ],
       [167978.5],
       [518211. ],
       [428955.5],
       [186308. ],
       [247277.5],
       [158511. ],
       [408452.5],
       [ 80996. ],
       [475984.5],
       [498418. ],
       [363186.5],
       [196816. ],
       [226087.5],
       [493994. ],
       [276430. ],
       [479318.5],
       [309449. ],
       [176858. ],
       [172462. ],
       [ 77167. ],
       [547378. ],
       [410516. ],
       [335093.5],
       [415231.5],
       [382241. ],
       [ 70862. ],
       [258300. ],
       [286937.5],
       [126791.5],
       [283248. ],
       [306690. ],
       [201073. ],
       [295002. ],
       [464634.5],
       [400027.5],
       [320391.5],
       [372595.5],
       [357294. ],
       [419748. ],
       [115351. ],
       [390915.5],
       [137169.5],
       [467471.5],
       [210661.5],
       [307770.5],
       [216327. ],
       [248983. ],
       [426760. ],
       [222063.5],
       [339888. ],
       [224745. ],
       [159309.5],
       [526502.5],
       [427496.5],
       [315542.5],
       [420403. ],
       [266983.5],
       [425960. ],
       [318951. ],
       [135309. ],
       [ 96554. ],
       [140216.5],
       [459686.5],
       [474562.5],
       [244287.5],
       [188582. ],
       [231291.5],
       [373529. ],
       [420631. ],
       [307993. ],
       [441395.5],
       [492951. ],
       [584267.5],
       [314149. ],
       [375097.5],
       [520659.5],
       [151474. ],
       [244295.5],
       [430451.5],
       [385248.5],
       [351201.5],
       [532570.5],
       [502519. ],
       [172234.5],
       [315914.5],
       [425083.5],
       [471527.5],
       [254581. ],
       [287588.5],
       [417693.5],
       [423231.5],
       [458591.5],
       [382461.5],
       [317119. ],
       [421781. ],
       [271956. ],
       [528770. ],
       [166571. ],
       [500903. ],
       [224958.5],
       [341328. ],
       [414938.5],
       [337257. ],
       [141833.5],
       [392864. ],
       [296829. ],
       [249765.5],
       [330281.5],
       [326161.5],
       [ 95533.5],
       [394208.5],
       [295406.5],
       [422774.5],
       [172758.5],
       [327994. ],
       [186356.5],
       [112604. ],
       [553855. ],
       [410877. ],
       [223778.5],
       [283184. ],
       [582347. ],
       [333278. ],
       [208573.5],
       [303419. ],
       [223594.5],
       [153381.5],
       [407127.5],
       [287093.5],
       [273761. ],
       [448905.5],
       [480307. ],
       [313049.5],
       [113700. ],
       [175102.5],
       [206999.5],
       [273707. ],
       [389925.5],
       [242950. ],
       [283435.5],
       [137514. ],
       [273659.5],
       [113942. ],
       [503648. ],
       [441104. ],
       [268314. ],
       [ 98254. ],
       [528634. ],
       [340429.5],
       [465338.5],
       [432951.5],
       [333672. ],
       [110021.5],
       [202503. ],
       [448106.5],
       [389099. ],
       [130233.5],
       [119387. ],
       [168940.5],
       [392097.5],
       [341076. ],
       [ 62737. ],
       [377706.5],
       [236994. ],
       [422417. ],
       [192576. ],
       [190744. ],
       [221972.5],
       [390305.5],
       [ 93713. ],
       [348535. ],
       [420102.5],
       [324899.5],
       [215386. ],
       [456653.5],
       [272816.5],
       [305589. ],
       [483884. ],
       [278759.5],
       [291031.5],
       [354409.5],
       [418504. ],
       [342427. ],
       [462715.5],
       [108354. ],
       [454168.5],
       [549406. ],
       [227845.5],
       [215633.5],
       [ 98489.5],
       [400606.5],
       [461900.5],
       [322368. ],
       [150234.5],
       [243565.5],
       [279833.5],
       [362434.5],
       [208189.5],
       [508087. ],
       [140798.5],
       [490779.5],
       [153375.5],
       [239018. ],
       [169674.5],
       [158250.5],
       [257565.5],
       [491123. ],
       [274650. ],
       [273728. ],
       [322204. ],
       [150074. ],
       [155719. ],
       [224359.5],
       [475273.5],
       [332812. ],
       [102144.5],
       [292308.5],
       [451307.5],
       [392920.5],
       [235843. ],
       [433615.5],
       [289570.5],
       [386141. ],
       [304923.5],
       [165595. ],
       [324260. ],
       [333133. ],
       [316827.5],
       [169471. ],
       [340961.5],
       [248119.5],
       [515454. ],
       [408405.5],
       [468543. ],
       [421679.5],
       [178520. ],
       [330887. ],
       [401500. ],
       [437043.5],
       [258692. ],
       [393351. ],
       [219462.5],
       [202883.5],
       [234142.5],
       [376375. ],
       [584116.5],
       [104215. ],
       [397522. ],
       [413540. ],
       [328973.5],
       [429837.5],
       [208468. ],
       [111185. ],
       [243097. ],
       [253530.5],
       [125454. ],
       [467395. ],
       [381846.5],
       [528607.5],
       [302011.5],
       [354722. ],
       [479031. ],
       [197377.5],
       [507799. ],
       [300499.5],
       [151836.5],
       [456154.5],
       [369571.5],
       [146787. ],
       [110883.5],
       [253387. ],
       [107500.5],
       [275670. ],
       [337327. ],
       [197430.5],
       [281037.5],
       [166283. ],
       [484480.5],
       [ 55925. ],
       [318148. ],
       [430469. ],
       [121022. ],
       [378132.5],
       [296565.5],
       [232192. ],
       [283208. ],
       [144191.5],
       [328863. ],
       [438223. ],
       [253476.5],
       [238941. ],
       [399672. ],
       [145880.5],
       [462499. ],
       [451290. ],
       [ 74863. ],
       [439639.5],
       [111175.5],
       [367122. ],
       [295021. ],
       [319728. ],
       [311773.5],
       [331687. ],
       [344539. ],
       [362377. ],
       [187009. ],
       [217446. ],
       [351704.5],
       [353318. ],
       [446875. ],
       [446300.5],
       [307255. ],
       [377575. ],
       [ 81507.5],
       [393104. ],
       [492753. ],
       [183833.5],
       [503606.5],
       [128489.5],
       [140884. ],
       [487717. ],
       [379566. ],
       [271010.5],
       [402812.5],
       [383875.5],
       [309455. ],
       [262090. ],
       [473834. ],
       [218908. ],
       [ 97280.5],
       [275045.5],
       [110359.5],
       [234835.5],
       [ 74398. ],
       [439864.5],
       [245594.5],
       [433504. ],
       [357823. ],
       [190956.5],
       [242273.5],
       [172415. ],
       [246460. ],
       [376267.5],
       [202702. ],
       [149141.5],
       [225917. ],
       [401745. ],
       [440044.5],
       [293424.5],
       [170960.5],
       [242173.5],
       [349762. ],
       [294378.5],
       [456840.5],
       [232826.5],
       [285487. ],
       [426479.5],
       [265194. ],
       [466398. ],
       [381351.5],
       [200794.5],
       [375118. ],
       [302423. ],
       [237730. ],
       [136824.5],
       [526394. ],
       [307096. ],
       [187050. ],
       [248738. ],
       [218665.5],
       [344339.5],
       [ 90220. ],
       [530759. ],
       [310987. ],
       [305463. ],
       [253037. ],
       [ 94467.5],
       [444625. ],
       [371227. ],
       [395188. ],
       [316652. ],
       [528418.5],
       [494542. ],
       [458139. ],
       [492171. ],
       [253055. ],
       [306660. ],
       [180891.5],
       [297886. ],
       [275757. ],
       [432836. ],
       [188186. ],
       [124183.5],
       [302878.5],
       [280209. ],
       [433627. ],
       [288926. ],
       [338141.5],
       [228892.5],
       [460019.5],
       [197714.5],
       [472972.5],
       [108223.5],
       [140796.5],
       [469956. ],
       [450198.5],
       [152125.5],
       [210777.5],
       [177748.5],
       [389512. ],
       [262126.5],
       [428602.5],
       [308220.5],
       [291815.5],
       [248248.5],
       [304104.5],
       [108894. ],
       [135874. ],
       [377108.5],
       [398513.5],
       [284727.5],
       [206296.5],
       [494575.5],
       [198892. ],
       [291776.5],
       [413288. ],
       [258268.5],
       [261568. ],
       [413954.5],
       [233139. ],
       [333655.5],
       [360737.5],
       [447337. ],
       [515167.5],
       [385196. ],
       [116254.5],
       [246242. ],
       [195854. ],
       [353237. ],
       [496293.5],
       [405950. ],
       [282418.5],
       [264084.5],
       [380928.5],
       [144272.5],
       [512492. ],
       [159614.5],
       [304818. ],
       [ 98311.5],
       [344820.5],
       [272075. ],
       [275837.5],
       [468666. ],
       [180912. ]], dtype=float32)>

In [33]:
from tensorflow.keras.layers import Normalization

In [34]:
normalizer = Normalization()
normalizer.adapt(X)
normalizer(X)

<tf.Tensor: shape=(1000, 8), dtype=float32, numpy=
array([[ 0.83749473, -0.88655   ,  1.4350008 , ...,  1.0948333 ,
        -0.22168264, -1.1603374 ],
       [-0.32650062,  0.21892546,  0.72177976, ...,  1.406057  ,
         1.3387846 , -0.35266685],
       [ 1.4194925 ,  1.5486262 ,  0.00855871, ...,  1.0948333 ,
        -1.5870914 , -0.1626267 ],
       ...,
       [ 1.4194925 ,  0.75239146, -1.4178834 , ...,  1.406057  ,
         0.46102175,  1.6902648 ],
       [ 1.4194925 , -1.0197191 , -1.4178834 , ...,  0.47238562,
        -0.51427025,  0.740064  ],
       [ 0.25549707,  1.1500455 ,  1.4350008 , ...,  0.99109197,
         0.7048448 ,  0.4550038 ]], dtype=float32)>

In [39]:
model = tf.keras.Sequential([normalizer, tf.keras.layers.Dense(1)])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 normalization (Normalizatio  (None, 8)                17
 n)

 dense (Dense)               (None, 1)                 9

=================================================================
Total params: 26
Trainable params: 9
Non-trainable params: 17
_________________________________________________________________

In [45]:
!pip install pydot

Collecting pydot
  Downloading pydot-1.4.2-py2.py3-none-any.whl (21 kB)
Requirement already satisfied: pyparsing>=2.1.4 in c:\users\yarkhan\anaconda3\lib\site-packages (from pydot) (3.0.4)
Installing collected packages: pydot
Successfully installed pydot-1.4.2

In [47]:
!pip install graphviz

Collecting graphviz
  Downloading graphviz-0.20.1-py3-none-any.whl (47 kB)
Installing collected packages: graphviz
Successfully installed graphviz-0.20.1

In [50]:
import pydot
import graphviz

In [52]:
tf.keras.utils.plot_model(model, show_shapes = True)

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.

In [ ]:
model.compile(loss = tf.keras.losses.mse, )